CALL SP_VEN_INSERTAR_DATOS_PRUEBA_REPORTE_VENDEDORES();
CALL SP_VEN_GENERAR_REPORTE_VENDEDORES (2025, 1);
CALL SP_VEN_GENERAR_REPORTE_VENDEDORES (2025, 2);
CALL SP_VEN_GENERAR_REPORTE_VENDEDORES (2025, 3);
#CALL SP_VEN_ELIMINAR_DATOS_PRUEBA_REPORTE_VENDEDORES();