DELIMITER $$
DROP PROCEDURE IF EXISTS SP_VEN_ELIMINAR_DATOS_PRUEBA_REPORTE_VENDEDORES$$

CREATE PROCEDURE `SP_VEN_ELIMINAR_DATOS_PRUEBA_REPORTE_VENDEDORES` ()
BEGIN    
	DELETE FROM VEN_REPORTES_VENDEDORES;
    DELETE FROM VEN_PERIODOS;
    DELETE FROM VEN_VENTAS_DETALLES;
    DELETE FROM VEN_VENTAS;    
    DELETE FROM VEN_TIPOS_DOCUMENTOS;
    DELETE FROM VEN_PRODUCTOS;
    DELETE FROM VEN_VENDEDORES;
    DELETE FROM VEN_TIENDAS;
END $$

DELIMITER ;
