--EXEC SP_INV_INSERTAR_DATOS_PRUEBA_REPORTE_STOCK;
EXEC SP_INV_GENERAR_REPORTE_STOCK 2025, 1;
EXEC SP_INV_GENERAR_REPORTE_STOCK 2025, 2;
EXEC SP_INV_GENERAR_REPORTE_STOCK 2025, 3;
--EXEC SP_INV_ELIMINAR_DATOS_PRUEBA_REPORTE_STOCK;