
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE SP_INV_ELIMINAR_DATOS_PRUEBA_REPORTE_STOCK
AS
BEGIN
	SET NOCOUNT ON;

    DELETE FROM INV_REPORTES_STOCKS;
    DELETE FROM INV_MOVIMIENTOS;
	DELETE FROM INV_PRODUCTOS;
    DELETE FROM INV_TIPOS_PRODUCTOS;
    DELETE FROM INV_TIPOS_DOCUMENTOS;
    DELETE FROM INV_ALMACENES;
    DELETE FROM INV_TIPOS_MOVIMIENTOS;
    DELETE FROM INV_PERIODOS;
END
GO
