CALL SP_INV_INSERTAR_DATOS_PRUEBA_REPORTE_STOCK();
CALL SP_INV_GENERAR_REPORTE_STOCK(2025, 01);
CALL SP_INV_GENERAR_REPORTE_STOCK(2025, 02);
CALL SP_INV_GENERAR_REPORTE_STOCK(2025, 03);
CALL SP_INV_ELIMINAR_DATOS_PRUEBA_REPORTE_STOCK();