DELIMITER $$
DROP PROCEDURE IF EXISTS SP_INV_ELIMINAR_DATOS_PRUEBA_REPORTE_STOCK$$

CREATE PROCEDURE `SP_INV_ELIMINAR_DATOS_PRUEBA_REPORTE_STOCK` ()
BEGIN    
	DELETE FROM INV_REPORTES_STOCKS;
    DELETE FROM INV_MOVIMIENTOS;
	DELETE FROM INV_PRODUCTOS;
    DELETE FROM INV_TIPOS_PRODUCTOS;
    DELETE FROM INV_TIPOS_DOCUMENTOS;
    DELETE FROM INV_ALMACENES;
    DELETE FROM INV_TIPOS_MOVIMIENTOS;
    DELETE FROM INV_PERIODOS;
END $$

DELIMITER ;

