SELECT r.ANHO, 
        r.MES, 
        a.ALMACEN_ID, 
        a.NOMBRE AS NOMBRE_ALMACEN, 
        a.ALMACEN_CENTRAL, 
        p.PRODUCTO_ID, 
        t.TIPO_PRODUCTO_ID, 
        t.NOMBRE AS NOMBRE_TIPO_PRODUCTO, 
        t.DESCRIPCION, 
        p.NOMBRE AS NOMBRE_PRODUCTO, 
        p.MARCA, 
        p.MODELO, 
        r.SALDO_INICIAL, 
        r.ENTRADAS, 
        r.SALIDAS, 
        r.SALDO_FINAL 
FROM INV_REPORTES_STOCKS r
JOIN INV_PRODUCTOS p ON p.PRODUCTO_ID = r.PRODUCTO_ID
JOIN INV_TIPOS_PRODUCTOS t on t.TIPO_PRODUCTO_ID = p.TIPO_PRODUCTO_ID
JOIN INV_ALMACENES a on a.ALMACEN_ID = r.ALMACEN_ID
WHERE r.ANHO = 2025 AND r.MES = 1